### ISSUE TITLE
Unknown tag glossary

### ISSUE THREAD

**Issue by cfranceschi-ledger** [erikw/jekyll-glossary_tooltip#5]
Hello!

The plugin is working when I use it locally, but it does not work on GitHub Pages.
I get the error "unknown tag glossary" at compilation as if the plugin was not installed.
Do you know what could cause this?

Thanks!

**Comment by erikw** [comment]
Hey, as I remember GitHub pages only support a limit set of Jekyll plugins. Please see

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins

I recommend checking out Netlify, they have a great free starter plan that works perfect with Jekyll

Here's a guide:

https://www.netlify.com/blog/2020/04/02/a-step-by-step-guide-jekyll-4.0-on-netlify/

Full disclosure: I do work at Netlify :)

**Comment by cfranceschi-ledger** [comment]
Thank you @erikw
